In [1]:
import pandas as pd
import numpy as numpy
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv("/content/loan_approval.csv")

In [3]:
df.isnull().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [8]:
df.tail()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [9]:
df.head()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False

In [10]:
df.columns

Index(['name', 'city', 'income', 'credit_score', 'loan_amount',
       'years_employed', 'points', 'loan_approved'],
      dtype='object')

In [30]:


x=df[[ 'income', 'credit_score','loan_amount','years_employed']]
y=df['loan_approved']

In [31]:
model=DecisionTreeClassifier()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [32]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [33]:
y_pred=model.predict(x_test)
acc=accuracy_score(y_test,y_pred)
acc

0.965

In [38]:
amount = int(input("Enter income: "))
score = int(input("Enter credit score: "))
loan = int(input("Enter loan amount: "))
years = int(input("Enter years employed: "))

pred = model.predict([[amount, score, loan, years]])[0]
print('predicted result: ', pred)

Enter income: 20000
Enter credit score: 350
Enter loan amount: 300000
Enter years employed: 5
predicted result:  False

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(